# Declaring a global site language and a country code
lang: en-US

# Excluded files from the compilation
exclude: ["node_modules", "gulpfile.js", "package.json", "README.md"]

# Base site url
baseurl:

# Version
version: 1.0.1

# Site title
title: Your New Jekyll Site
