# Declaring a global site language and a country code
lang: en-US

# Excluded files from the compilation
exclude: ["node_modules", "gulpfile.js", "package.json", "README.md"]

# Base site url
baseurl:
url: "https://garbot.github.io/"

# Version
version: 1.0.2

# Site title
title: Garrett Sitter
# Website language
lang: en-US
# Header Title
header-title: Raleigh, NC based web developer
# Header Tagline
headter-tagline: Garrett Sitter

###########
## Links ##
###########
#youtube: '#'
#pinterest: '#'
#facebook: '#'
#twitter: '#
linkedin: 'garrett-sitter-94b59b126'
#reddit: '#'
github: 'https://github.com/Garbot'
stackoverflow: 'https://stackoverflow.com/users/5670520/garrett-sitter'
codepen: 'https://codepen.io/garbot/'
#google-plus: '#'
#vimeo: '#'

#####################################
############  Portfolio  ############
#####################################

portfolio-title: Projects
portfolio-description: Here are some things that I've built.

portfolio:

# Portfolio Item
- title: Hongry
  image: port1.png
  description: 'Location based restaurant locator'
  url: 'https://www.hongry.xyz'

# Portfolio Item
- title: Garrett Sitter - Portfolio Site
  image: port2.png
  description: 'You\'re looking at it!'
  url: 'https://garbot.github.io'
  
# Portfolio Item
- title: Tic Tac Toe AI
  image: port3.png
  description: 'Experiment in building an unbeatable Tic Tac Toe AI'
  url: 'https://codepen.io/garbot/pen/bWLGGL'
  
# Portfolio Item
#- title: tetris.js
#  image: port4.png
#  description: 'Browser based tetris game built using HTML5 Canvas and vanilla Javascript'
#  url: 'http://tetris.js.s3-website-us-east-1.amazonaws.com/'
  
# Portfolio Item
#- title: Simon Extreme
#  image: port5.png
#  description: 'Skateboard and Mountain Dew optional.  Game built with dynamically generated interactive SVG'
#  url: 'https://codepen.io/garbot/pen/BRqXay'

# Portfolio Item
#- title: Twitquote
#  image: port6.png
#  description: 'Simple node.js app that retrieves a random tweet from a specified user'
#  url: ''
  
# Portfolio Item
#- title: Pomodoro
#  image: port7.png
#  description: 'Browser based pomodoro timer'
#  url: 'https://codepen.io/garbot/pen/NpXVPV'
  
# Portfolio Item
#- title: Reddit Clone
#  image: port8.png
#  description: 'Reddit clone - built in meteor.js'
#  url: ''
  
#####################################
#############   Footer   ############
#####################################
#footer-copyright-text: Garrett Sitter
#footer-copyright-url: https://garbot.github.io
#footer-copyright-year: 2017

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""