# Declaring a global site language and a country code
lang: en-US

# Excluded files from the compilation
exclude: ["node_modules", "gulpfile.js", "package.json", "README.md"]

# Base site url
baseurl:
url: "https://garbot.github.io/"

# Collections
collections:
- portfolio

# Version
version: 1.0.2

# Site title
title: Garrett Sitter

# Website language
lang: en-US

# Header Title
header-title: Garrett Sitter
# Header Tagline
header-tagline: Web Developer - Raleigh, NC


###########
## Links ##
###########
#youtube: '#'
#pinterest: '#'
#facebook: '#'
#twitter: '#
linkedin: 'https://www.linkedin.com/in/garrett-sitter-94b59b126'
#reddit: '#'
github: 'https://github.com/Garbot'
stackoverflow: 'https://stackoverflow.com/users/5670520/garrett-sitter'
codepen: 'https://codepen.io/garbot/'
#google-plus: '#'
#vimeo: '#'



#####################################
#############   Footer   ############
#####################################
#footer-copyright-text: Garrett Sitter
#footer-copyright-url: https://garbot.github.io
#footer-copyright-year: 2017

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""
